version: '3.8'

services:
  angular:
    container_name: angular-image
    build: ./frontend
    volumes: 
      - ./frontend:/app
    ports: 
      - 4200:80
    
  django:
    container_name: django-image
    build: ./backend/CRUD/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/CRUD:/backend
    ports: 
      - 8000:8000