version: '3.8'

services:
  angular:
    hostname: localhost
    build: 
      context: /frontend
    volumes: 
      - .:/app
    ports: 
      - 4200:4200
    
  django:
    build: 
      context: ./backend/CRUD
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    ports: 
      - 8000:8000