version: '3.8'

services:
  angular:
    hostname: localhost
    build: frontend
    ports: 
      - 4200:4200
  django:
    build: backend/CRUD
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - 8000:8000