# Generated by Django 3.1.6 on 2021-02-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('year', models.DateField()),
            ],
            options={
                'ordering': ('brand',),
            },
        ),
    ]
