# Generated by Django 3.1.6 on 2021-02-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210205_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.DateField(),
        ),
    ]
